name: publish-jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.15.1"
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_API_TOKEN }}
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/yuanssai/yuansaiapis.git#branch=main"
      - run: buf generate --template templates/buf.java.gen.yaml
      - run: mv templates/build.gradle gen/
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          JAR_VERSION: ${{ steps.vars.outputs.sha_short }}
        with:
          gradle-version: release-candidate
          arguments: publish -b gen/build.gradle
      - name: Version
        run: |
          SUMMARY=$'# Version Summary\n${{ steps.vars.outputs.sha_short }}'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
