name: Test latest Gradle RC
on:
  push:
    branches:
      - main
jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - run: gradle build --dry-run # just test build configuration